--- # Common playbook

  - name : Getting VGS Name
    shell: "/sbin/vgs|grep applvg|cut -d' ' -f3"
    register: vg_name

  - name: Creating Logical Volume
    lvol:
      vg: "{{vg_name.stdout}}"
      lv: "{{item.lvname}}"
      size: "{{item.lvsize}}"
    with_items: "{{demo.fs}}"

  - name: Creating FileSystem
    filesystem:
       fstype: ext4
       dev: "/dev/{{vg_name.stdout}}/{{item.lvname}}"
    with_items: "{{demo.fs}}"

  - name: Mounting FileSystem
    mount:
       src: "/dev/{{vg_name.stdout}}/{{item.lvname}}"
       name: "{{item.mount}}"
       fstype: ext4
       state: mounted
    with_items: "{{demo.fs}}"


#### changing the ownership to root  ####
  - name : changing ownership of  mountpoints
    file:
      path: "{{item.mount}}"
      owner: root
      group: root
      mode: 0755
    with_items: "{{demo.fs}}"
